#!/usr/bin/env python3

global num_actions 
global num_states
global angle_max
global angle_min
global yaw_max
global yaw_min
global max_vel_up
global max_vel_down
global gamma
global tau
global buffer
global actor_model
global critic_model
global target_actor
global target_critic
global critic_optimizer
global actor_optimizer
global ep_reward_list
global avg_reward_list
global episodes
global ou_noise